# Generated by Django 5.2.3 on 2025-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('pasajero', 'Pasajero')], default='pasajero', max_length=20),
        ),
    ]
