# Generated by Django 5.2.3 on 2025-10-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='documento',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='pasajero',
            constraint=models.UniqueConstraint(fields=('documento', 'is_active'), name='uniq_pasajero_documento_while_active'),
        ),
    ]
