# Generated by Django 5.2.3 on 2025-07-31 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasajeros', '0001_initial'),
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.CharField(max_length=1)),
                ('tipo', models.CharField(choices=[('ventana', 'Ventana'), ('pasillo', 'Pasillo'), ('medio', 'Medio')], max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.asiento')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pasajeros.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
