# Generated by Django 5.2.3 on 2025-08-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.avion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='reservas.asiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
