# Generated by Django 5.2.3 on 2025-10-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asientovuelo',
            unique_together={('vuelo', 'asiento')},
        ),
    ]
