# Generated by Django 5.2.3 on 2025-10-31 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
        ('reservas', '0002_alter_asientovuelo_unique_together'),
        ('vuelos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asiento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asiento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asientovuelo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='vuelos.avion'),
        ),
        migrations.AlterField(
            model_name='asientovuelo',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.asiento'),
        ),
        migrations.AlterField(
            model_name='asientovuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_vuelo', to='vuelos.vuelo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='pasajeros.pasajero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vuelos.vuelo'),
        ),
    ]
