# Generated by Django 5.2.3 on 2025-06-26 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('filas', models.PositiveIntegerField()),
                ('columnas', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En Vuelo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='vuelos.avion')),
                ('usuarios_gestores', models.ManyToManyField(related_name='vuelos_gestionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha_salida'],
            },
        ),
    ]
