# Generated by Django 5.2.3 on 2025-08-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='id',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
