# Generated by Django 5.2.3 on 2025-11-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_avion_deleted_at_avion_deleted_by_avion_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.avion'),
        ),
    ]
